version: '3'

services:
  db_sv_account:
    image: mysql:latest
    environment:
      - 'MYSQL_DATABASE=db_sv_account'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=account'
    networks:
      - private

  db_sv_customer:
    image: mysql:latest
    environment:
      - 'MYSQL_DATABASE=db_sv_customer'
      - 'MYSQL_PASSWORD=password'
      - 'MYSQL_ROOT_PASSWORD=root'
      - 'MYSQL_USER=customer'
    networks:
      - private

networks:
  private:
    external: true